name: movie_list

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.4
  nil: ^1.1.1
  go_router: ^7.0.1
  meta: any
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  cached_network_image: ^3.2.2
  internet_connection_checker_plus: ^1.0.1
  connectivity_plus: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/jpg/
    - assets/svg/
